name: Sync to QA Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to QA repo
        env:
          QA_TOKEN: ${{ secrets.TOKEN_QA }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote add qa https://x-access-token:${QA_TOKEN}@github.com/CESARBR2025/sjr-qa-tramites-sare-next.git

          git ls-remote https://x-access-token:${QA_TOKEN}@github.com/CESARBR2025/sjr-qa-tramites-sare-next.git

          git push qa main --force
